global proc AEgfUtilAngleScalarMathTemplate(string $nodeName){
    editorTemplate -beginScrollLayout;
        editorTemplate -beginLayout "gfUtilAngleScalarMath Attributes" -collapse 0;
            editorTemplate -addControl "operation";
            editorTemplate -addControl "angle";
            editorTemplate -addControl "scalar";
        editorTemplate -endLayout;
        AEdependNodeTemplate $nodeName;
    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;
}