global proc AEgfUtilAngleTrigMathTemplate(string $nodeName){
    editorTemplate -beginScrollLayout;
        editorTemplate -beginLayout "gfUtilAngleTrigMath Attributes" -collapse 0;
            editorTemplate -addControl "operation";
            editorTemplate -addControl "angle1";
            editorTemplate -addControl "angle2";
        editorTemplate -endLayout;
        AEdependNodeTemplate $nodeName;
    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;
}