global proc AEgfAimConstraintTemplate(string $nodeName){
    editorTemplate -beginScrollLayout;
        editorTemplate -beginLayout "gfAimConstraint Attributes" -collapse 0;
            editorTemplate -beginLayout "Up Vector Options" -collapse 0;
                editorTemplate -addControl "upVectorType";
                editorTemplate -addControl "worldUpVector";
                editorTemplate -addControl "angleUp";
                editorTemplate -addSeparator;
                editorTemplate -addControl "offset";
                editorTemplate -addControl "targetWeight";
                editorTemplate -addControl "constraintRotateOrder";
                editorTemplate -addControl "constraintJointOrient";
            editorTemplate -endLayout;
            editorTemplate -beginLayout "Input Matrices" -collapse 1;
                editorTemplate -addControl "worldUpMatrix";
                editorTemplate -addControl "targetWorldMatrix";
                editorTemplate -addControl "constraintWorldMatrix";
                editorTemplate -addControl "constraintParentInverseMatrix";
            editorTemplate -endLayout;
        editorTemplate -endLayout;
        AEdependNodeTemplate $nodeName;
    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;
}