import weakref
import shiboken2
from PySide2 import QtWidgets, QtCore, QtGui
from maya import cmds
from maya import OpenMayaUI as omui
from maya.app.general.mayaMixin import MayaQWidgetDockableMixin


class dockWindow(MayaQWidgetDockableMixin, QtWidgets.QMainWindow):
    DOCK_LABEL_NAME = 'gfCustomDock'
    CONTROL_NAME = 'gfCustomDockWin'
    instances = list()

    def __init__(self):
        super(dockWindow, self).__init__()
        dockWindow.deleteInstances()
        self.__class__.instances.append(weakref.proxy(self))
        # Not sure, but I suppose that we better keep track of instances of our window and keep Maya environment clean.
        # So we'll remove all instances before creating a new one.
        if cmds.window(self.CONTROL_NAME + "WorkspaceControl", ex=True): # workspaceControl
            print("Removing", self.CONTROL_NAME + "WorkspaceControl")
            cmds.deleteUI(self.CONTROL_NAME + "WorkspaceControl") # cmds.workspaceControl(control, e=True, close=True) | cmds.deleteUI(control, control=True)
            print("Removed", self.CONTROL_NAME + "WorkspaceControl")
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose, True)
        # Set object name and window title
        self.setupUi(self)

    @staticmethod
    def deleteInstances():
        for ins in dockWindow.instances:
            try:
                print('Delete {}'.format(ins))
            except:
                print('Window reference seems to be removed already, ignore.')
            try:
                ins.setParent(None)
                ins.deleteLater()
            except:
                # ignore the fact that the actual parent has already been deleted by Maya...
                pass
            try:
                dockWindow.instances.remove(ins)
                del ins
            except:
                # Supress error
                pass
    def setupUi(self, window):
        pass


def getMainWindow():
    """
    Get main Maya window instance.
    """
    mayaMainWindowPtr = omui.MQtUtil.mainWindow()
    mayaMainWindow = shiboken2.wrapInstance(long(mayaMainWindowPtr), QMainWindow)
    mayaMainWindow.setWindowTitle("MEUCU")
    return mayaMainWindow


def dock_window(dialog_class, width=440):
    """
    This function is to be updates to actually dock window on creation to the right.
    """
    dock_win = dialog_class()
    dock_win.show(dockable=True)
    return dock_win


def show_test():
    # This is how to call and show a window
    ChildTestWindow().show(dockable=True)


class ChildTestWindow(dockWindow):
    """
    Example child window inheriting from main class.
    """
    DOCK_LABEL_NAME = 'child test window'  # Window display name
    instances = list()
    CONTROL_NAME = 'child_test_win'  # Window unique object name
    def __init__(self):
        super(ChildTestWindow, self).__init__()

    def setupUi(self, window):
        window.setObjectName(self.CONTROL_NAME)
        window.resize(1042, 583)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget_folderList = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget_folderList.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.treeWidget_folderList.setAlternatingRowColors(True)
        self.treeWidget_folderList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget_folderList.setHeaderHidden(True)
        self.treeWidget_folderList.setObjectName("treeWidget_folderList")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_folderList)
        self.scrollArea_pose = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea_pose.setWidgetResizable(True)
        self.scrollArea_pose.setObjectName("scrollArea_pose")
        self.scrollAreaWidget_pose = QtWidgets.QWidget()
        self.scrollAreaWidget_pose.setGeometry(QtCore.QRect(0, 0, 394, 563))
        self.scrollAreaWidget_pose.setObjectName("scrollAreaWidget_pose")
        self.gridLayout_poseList = QtWidgets.QGridLayout(self.scrollAreaWidget_pose)
        self.gridLayout_poseList.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_poseList.setSpacing(10)
        self.gridLayout_poseList.setObjectName("gridLayout_poseList")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_poseList.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_poseList.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_poseList.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_poseList.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_poseList.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_poseList.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_poseList.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_poseList.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_poseList.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_poseList.addWidget(self.pushButton_11, 3, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_poseList.addWidget(self.pushButton_12, 3, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_poseList.addWidget(self.pushButton_10, 3, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_poseList.addWidget(self.pushButton_14, 4, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_poseList.addWidget(self.pushButton_15, 4, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidget_pose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_poseList.addWidget(self.pushButton_13, 4, 2, 1, 1)
        self.scrollArea_pose.setWidget(self.scrollAreaWidget_pose)
        self.groupBox_pose = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_pose.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox_pose.setObjectName("groupBox_pose")
        self.verticalLayout_pose = QtWidgets.QVBoxLayout(self.groupBox_pose)
        self.verticalLayout_pose.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_pose.setSpacing(10)
        self.verticalLayout_pose.setObjectName("verticalLayout_pose")
        self.groupBox_snapShot = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_snapShot.setObjectName("groupBox_snapShot")
        self.horizontalLayout_snapShot = QtWidgets.QHBoxLayout(self.groupBox_snapShot)
        self.horizontalLayout_snapShot.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_snapShot.setSpacing(5)
        self.horizontalLayout_snapShot.setObjectName("horizontalLayout_snapShot")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_snapShot.addItem(spacerItem)
        self.button_snapShot = QtWidgets.QPushButton(self.groupBox_snapShot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_snapShot.sizePolicy().hasHeightForWidth())
        self.button_snapShot.setSizePolicy(sizePolicy)
        self.button_snapShot.setMinimumSize(QtCore.QSize(150, 150))
        self.button_snapShot.setObjectName("button_snapShot")
        self.horizontalLayout_snapShot.addWidget(self.button_snapShot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_snapShot.addItem(spacerItem1)
        self.verticalLayout_pose.addWidget(self.groupBox_snapShot)
        self.groupBox_poseLabel = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_poseLabel.setObjectName("groupBox_poseLabel")
        self.horizontalLayout_poseLabel = QtWidgets.QHBoxLayout(self.groupBox_poseLabel)
        self.horizontalLayout_poseLabel.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_poseLabel.setSpacing(5)
        self.horizontalLayout_poseLabel.setObjectName("horizontalLayout_poseLabel")
        self.label_poseLabel = QtWidgets.QLabel(self.groupBox_poseLabel)
        self.label_poseLabel.setObjectName("label_poseLabel")
        self.horizontalLayout_poseLabel.addWidget(self.label_poseLabel)
        self.lineEdit_poseLabel = QtWidgets.QLineEdit(self.groupBox_poseLabel)
        self.lineEdit_poseLabel.setObjectName("lineEdit_poseLabel")
        self.horizontalLayout_poseLabel.addWidget(self.lineEdit_poseLabel)
        self.verticalLayout_pose.addWidget(self.groupBox_poseLabel)
        self.textEdit_history = QtWidgets.QTextEdit(self.groupBox_pose)
        self.textEdit_history.setReadOnly(True)
        self.textEdit_history.setObjectName("textEdit_history")
        self.verticalLayout_pose.addWidget(self.textEdit_history)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_pose.addItem(spacerItem2)
        self.groupBox_blend = QtWidgets.QGroupBox(self.groupBox_pose)
        self.groupBox_blend.setObjectName("groupBox_blend")
        self.horizontalLayout_blend = QtWidgets.QHBoxLayout(self.groupBox_blend)
        self.horizontalLayout_blend.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_blend.setSpacing(5)
        self.horizontalLayout_blend.setObjectName("horizontalLayout_blend")
        self.slider_poseBlend = QtWidgets.QSlider(self.groupBox_blend)
        self.slider_poseBlend.setOrientation(QtCore.Qt.Horizontal)
        self.slider_poseBlend.setObjectName("slider_poseBlend")
        self.horizontalLayout_blend.addWidget(self.slider_poseBlend)
        self.button_blendValue = QtWidgets.QPushButton(self.groupBox_blend)
        self.button_blendValue.setMinimumSize(QtCore.QSize(50, 30))
        self.button_blendValue.setMaximumSize(QtCore.QSize(50, 30))
        self.button_blendValue.setObjectName("button_blendValue")
        self.horizontalLayout_blend.addWidget(self.button_blendValue)
        self.verticalLayout_pose.addWidget(self.groupBox_blend)
        self.button_save = QtWidgets.QPushButton(self.groupBox_pose)
        self.button_save.setObjectName("button_save")
        self.verticalLayout_pose.addWidget(self.button_save)
        self.verticalLayout.addWidget(self.splitter)
        window.setCentralWidget(self.centralwidget)
        self.action_createFolder = QtWidgets.QAction(window)
        self.action_createFolder.setObjectName("action_createFolder")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget_folderList.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget_folderList.isSortingEnabled()
        self.treeWidget_folderList.setSortingEnabled(False)
        self.treeWidget_folderList.topLevelItem(0).setText(0, _translate("MainWindow", "A"))
        self.treeWidget_folderList.setSortingEnabled(__sortingEnabled)
        self.groupBox_pose.setTitle(_translate("MainWindow", "Pose"))
        self.button_snapShot.setText(_translate("MainWindow", "Icon"))
        self.label_poseLabel.setText(_translate("MainWindow", "Name"))
        self.button_blendValue.setText(_translate("MainWindow", "0"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.action_createFolder.setText(_translate("MainWindow", "Create Folder"))
