# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gfutilitiesbelt_addpocket.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

import sys
from PySide2 import QtCore, QtGui, QtWidgets
from maya import cmds
from maya.app.general.mayaMixin import MayaQWidgetBaseMixin

class Ui_gfutilitiesbelt_addpocketUI(MayaQWidgetBaseMixin, QtWidgets.QDialog):
    def __init__(self, parent=None):
        self.CONTROL_NAME = "gfutilitiesbelt_addpocketUI"
        super(Ui_gfutilitiesbelt_addpocketUI, self).__init__(parent=parent)
        if cmds.window(self.CONTROL_NAME, ex=True):
            cmds.deleteUI(self.CONTROL_NAME)
        self.setupUi()

    def setupUi(self):
        self.setObjectName(self.CONTROL_NAME)
        self.resize(550, 350)
        self.lay_central = QtWidgets.QVBoxLayout(self)
        self.lay_central.setContentsMargins(1, 1, 1, 1)
        self.lay_central.setSpacing(1)
        self.lay_central.setObjectName("lay_central")
        self.wdg_titleArea = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_titleArea.sizePolicy().hasHeightForWidth())
        self.wdg_titleArea.setSizePolicy(sizePolicy)
        self.wdg_titleArea.setMinimumSize(QtCore.QSize(0, 50))
        self.wdg_titleArea.setObjectName("wdg_titleArea")
        self.lay_titleArea = QtWidgets.QHBoxLayout(self.wdg_titleArea)
        self.lay_titleArea.setContentsMargins(10, 10, 10, 10)
        self.lay_titleArea.setSpacing(3)
        self.lay_titleArea.setObjectName("lay_titleArea")
        self.lbl_info = QtWidgets.QLabel(self.wdg_titleArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_info.sizePolicy().hasHeightForWidth())
        self.lbl_info.setSizePolicy(sizePolicy)
        self.lbl_info.setMinimumSize(QtCore.QSize(140, 0))
        self.lbl_info.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lbl_info.setObjectName("lbl_info")
        self.lay_titleArea.addWidget(self.lbl_info)
        self.lbl_titleArrow = QtWidgets.QLabel(self.wdg_titleArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_titleArrow.sizePolicy().hasHeightForWidth())
        self.lbl_titleArrow.setSizePolicy(sizePolicy)
        self.lbl_titleArrow.setMinimumSize(QtCore.QSize(20, 0))
        self.lbl_titleArrow.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_titleArrow.setObjectName("lbl_titleArrow")
        self.lay_titleArea.addWidget(self.lbl_titleArrow)
        self.lbl_title = QtWidgets.QLabel(self.wdg_titleArea)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.lay_titleArea.addWidget(self.lbl_title)
        self.lay_central.addWidget(self.wdg_titleArea)
        self.wdg_contentArea = QtWidgets.QWidget(self)
        self.wdg_contentArea.setObjectName("wdg_contentArea")
        self.lay_contentArea = QtWidgets.QHBoxLayout(self.wdg_contentArea)
        self.lay_contentArea.setContentsMargins(1, 1, 1, 1)
        self.lay_contentArea.setSpacing(1)
        self.lay_contentArea.setObjectName("lay_contentArea")
        self.wdg_inputArea = QtWidgets.QWidget(self.wdg_contentArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_inputArea.sizePolicy().hasHeightForWidth())
        self.wdg_inputArea.setSizePolicy(sizePolicy)
        self.wdg_inputArea.setMinimumSize(QtCore.QSize(320, 295))
        self.wdg_inputArea.setObjectName("wdg_inputArea")
        self.lay_inputArea = QtWidgets.QVBoxLayout(self.wdg_inputArea)
        self.lay_inputArea.setContentsMargins(1, 1, 1, 1)
        self.lay_inputArea.setSpacing(1)
        self.lay_inputArea.setObjectName("lay_inputArea")
        self.wdg_settingsArea = QtWidgets.QWidget(self.wdg_inputArea)
        self.wdg_settingsArea.setObjectName("wdg_settingsArea")
        self.lay_settingsArea = QtWidgets.QVBoxLayout(self.wdg_settingsArea)
        self.lay_settingsArea.setContentsMargins(1, 1, 1, 1)
        self.lay_settingsArea.setSpacing(1)
        self.lay_settingsArea.setObjectName("lay_settingsArea")
        self.wdg_nameArea = QtWidgets.QWidget(self.wdg_settingsArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_nameArea.sizePolicy().hasHeightForWidth())
        self.wdg_nameArea.setSizePolicy(sizePolicy)
        self.wdg_nameArea.setMaximumSize(QtCore.QSize(16777215, 25))
        self.wdg_nameArea.setObjectName("wdg_nameArea")
        self.lay_nameArea = QtWidgets.QHBoxLayout(self.wdg_nameArea)
        self.lay_nameArea.setContentsMargins(10, 1, 1, 1)
        self.lay_nameArea.setSpacing(6)
        self.lay_nameArea.setObjectName("lay_nameArea")
        self.lbl_name = QtWidgets.QLabel(self.wdg_nameArea)
        self.lbl_name.setObjectName("lbl_name")
        self.lay_nameArea.addWidget(self.lbl_name)
        self.txt_name = QtWidgets.QLineEdit(self.wdg_nameArea)
        self.txt_name.setClearButtonEnabled(True)
        self.txt_name.setObjectName("txt_name")
        self.lay_nameArea.addWidget(self.txt_name)
        self.btn_import = QtWidgets.QPushButton(self.wdg_nameArea)
        self.btn_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_import.setObjectName("btn_import")
        self.lay_nameArea.addWidget(self.btn_import)
        self.lay_settingsArea.addWidget(self.wdg_nameArea)
        self.wdg_importArea = QtWidgets.QWidget(self.wdg_settingsArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_importArea.sizePolicy().hasHeightForWidth())
        self.wdg_importArea.setSizePolicy(sizePolicy)
        self.wdg_importArea.setMinimumSize(QtCore.QSize(0, 25))
        self.wdg_importArea.setObjectName("wdg_importArea")
        self.lay_importArea = QtWidgets.QHBoxLayout(self.wdg_importArea)
        self.lay_importArea.setContentsMargins(10, 1, 1, 1)
        self.lay_importArea.setSpacing(6)
        self.lay_importArea.setObjectName("lay_importArea")
        self.lbl_fileTitle = QtWidgets.QLabel(self.wdg_importArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_fileTitle.sizePolicy().hasHeightForWidth())
        self.lbl_fileTitle.setSizePolicy(sizePolicy)
        self.lbl_fileTitle.setObjectName("lbl_fileTitle")
        self.lay_importArea.addWidget(self.lbl_fileTitle)
        self.lbl_importedFile = QtWidgets.QLabel(self.wdg_importArea)
        self.lbl_importedFile.setText("")
        self.lbl_importedFile.setObjectName("lbl_importedFile")
        self.lay_importArea.addWidget(self.lbl_importedFile)
        self.btn_cancelImport = QtWidgets.QPushButton(self.wdg_importArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancelImport.sizePolicy().hasHeightForWidth())
        self.btn_cancelImport.setSizePolicy(sizePolicy)
        self.btn_cancelImport.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_cancelImport.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_cancelImport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelImport.setStyleSheet("background-color: transparent;\n"
"border: None;")
        self.btn_cancelImport.setObjectName("btn_cancelImport")
        self.btn_cancelImport.setEnabled(False)
        self.lay_importArea.addWidget(self.btn_cancelImport)
        self.lay_settingsArea.addWidget(self.wdg_importArea)
        self.wdg_toolsArea = QtWidgets.QWidget(self.wdg_settingsArea)
        self.wdg_toolsArea.setEnabled(True)
        self.wdg_toolsArea.setObjectName("wdg_toolsArea")
        self.lay_toolsArea = QtWidgets.QHBoxLayout(self.wdg_toolsArea)
        self.lay_toolsArea.setContentsMargins(1, 1, 1, 1)
        self.lay_toolsArea.setSpacing(3)
        self.lay_toolsArea.setObjectName("lay_toolsArea")
        self.lst_tools = QtWidgets.QListWidget(self.wdg_toolsArea)
        self.lst_tools.setObjectName("lst_tools")
        self.lst_tools.setAlternatingRowColors(True)
        self.lst_tools.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lay_toolsArea.addWidget(self.lst_tools)
        self.wdg_selectArea = QtWidgets.QWidget(self.wdg_toolsArea)
        self.wdg_selectArea.setObjectName("wdg_selectArea")
        self.lay_selectArea = QtWidgets.QVBoxLayout(self.wdg_selectArea)
        self.lay_selectArea.setContentsMargins(0, 0, 0, 0)
        self.lay_selectArea.setSpacing(6)
        self.lay_selectArea.setObjectName("lay_selectArea")
        self.btn_addTool = QtWidgets.QPushButton(self.wdg_selectArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addTool.sizePolicy().hasHeightForWidth())
        self.btn_addTool.setSizePolicy(sizePolicy)
        self.btn_addTool.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_addTool.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_addTool.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_addTool.setObjectName("btn_addTool")
        self.lay_selectArea.addWidget(self.btn_addTool)
        self.btn_removeTool = QtWidgets.QPushButton(self.wdg_selectArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_removeTool.sizePolicy().hasHeightForWidth())
        self.btn_removeTool.setSizePolicy(sizePolicy)
        self.btn_removeTool.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_removeTool.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_removeTool.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_removeTool.setObjectName("btn_removeTool")
        self.lay_selectArea.addWidget(self.btn_removeTool)
        self.lay_toolsArea.addWidget(self.wdg_selectArea)
        self.lay_settingsArea.addWidget(self.wdg_toolsArea)
        self.lay_inputArea.addWidget(self.wdg_settingsArea)
        self.wdg_outputArea = QtWidgets.QWidget(self.wdg_inputArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_outputArea.sizePolicy().hasHeightForWidth())
        self.wdg_outputArea.setSizePolicy(sizePolicy)
        self.wdg_outputArea.setMinimumSize(QtCore.QSize(0, 25))
        self.wdg_outputArea.setObjectName("wdg_outputArea")
        self.lay_outputArea = QtWidgets.QHBoxLayout(self.wdg_outputArea)
        self.lay_outputArea.setContentsMargins(1, 1, 1, 1)
        self.lay_outputArea.setSpacing(6)
        self.lay_outputArea.setObjectName("lay_outputArea")
        self.btn_cancel = QtWidgets.QPushButton(self.wdg_outputArea)
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lay_outputArea.addWidget(self.btn_cancel)
        self.btn_create = QtWidgets.QPushButton(self.wdg_outputArea)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setObjectName("btn_create")
        self.btn_create.setShortcut(QtGui.QKeySequence("Return"))
        self.lay_outputArea.addWidget(self.btn_create)
        self.lay_inputArea.addWidget(self.wdg_outputArea)
        self.lay_contentArea.addWidget(self.wdg_inputArea)
        self.wdg_previewArea = QtWidgets.QWidget(self.wdg_contentArea)
        self.wdg_previewArea.setMinimumSize(QtCore.QSize(220, 0))
        self.wdg_previewArea.setObjectName("wdg_previewArea")
        self.lay_previewArea = QtWidgets.QVBoxLayout(self.wdg_previewArea)
        self.lay_previewArea.setContentsMargins(1, 1, 1, 1)
        self.lay_previewArea.setSpacing(1)
        self.lay_previewArea.setObjectName("lay_previewArea")
        self.lst_preview = QtWidgets.QListWidget(self.wdg_previewArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_preview.sizePolicy().hasHeightForWidth())
        self.lst_preview.setSizePolicy(sizePolicy)
        self.lst_preview.setObjectName("lst_preview")
        self.lay_previewArea.addWidget(self.lst_preview)
        self.lay_contentArea.addWidget(self.wdg_previewArea)
        self.lay_central.addWidget(self.wdg_contentArea)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, gfutilitiesbelt_addpocketUI):
        _translate = QtCore.QCoreApplication.translate
        gfutilitiesbelt_addpocketUI.setWindowTitle(_translate(self.CONTROL_NAME, "gfUtilitiesBelt - Add Pocket"))
        self.lbl_info.setText(_translate(self.CONTROL_NAME, "               Advanced Create"))
        self.lbl_titleArrow.setText(_translate(self.CONTROL_NAME, ">"))
        self.lbl_title.setText(_translate(self.CONTROL_NAME, "Create a new pocket"))
        self.lbl_name.setText(_translate(self.CONTROL_NAME, "Name:"))
        self.btn_import.setText(_translate(self.CONTROL_NAME, "Import"))
        self.lbl_fileTitle.setText(_translate(self.CONTROL_NAME, "Imported file:"))
        self.btn_cancelImport.setText(_translate(self.CONTROL_NAME, "X"))
        self.btn_addTool.setText(_translate(self.CONTROL_NAME, "+"))
        self.btn_removeTool.setText(_translate(self.CONTROL_NAME, "-"))
        self.btn_cancel.setText(_translate(self.CONTROL_NAME, "Cancel"))
        self.btn_create.setText(_translate(self.CONTROL_NAME, "Create"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     gfutilitiesbelt_addpocketUI = QtWidgets.QDialog()
#     ui = Ui_gfutilitiesbelt_addpocketUI()
#     ui.setupUi(gfutilitiesbelt_addpocketUI)
#     gfutilitiesbelt_addpocketUI.show()
#     sys.exit(app.exec_())
