# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gfutilitiesbelt_editpocket.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

import sys
from PySide2 import QtCore, QtGui, QtWidgets
from maya import cmds
from maya.app.general.mayaMixin import MayaQWidgetBaseMixin

class Ui_gfutilitiesbelt_editpocketUI(MayaQWidgetBaseMixin, QtWidgets.QDialog):
    def __init__(self, parent=None):
        self.CONTROL_NAME = "gfutilitiesbelt_editpocketUI"
        super(Ui_gfutilitiesbelt_editpocketUI, self).__init__(parent=parent)
        if cmds.workspaceControl(self.CONTROL_NAME + 'WorkspaceControl', ex=True):
            cmds.deleteUI(self.CONTROL_NAME + 'WorkspaceControl')
        self.setupUi()

    def setupUi(self):
        self.setObjectName(self.CONTROL_NAME)
        self.resize(550, 350)
        self.lay_central = QtWidgets.QVBoxLayout(self)
        self.lay_central.setContentsMargins(1, 1, 1, 1)
        self.lay_central.setSpacing(1)
        self.lay_central.setObjectName("lay_central")
        self.wdg_titleArea = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_titleArea.sizePolicy().hasHeightForWidth())
        self.wdg_titleArea.setSizePolicy(sizePolicy)
        self.wdg_titleArea.setMinimumSize(QtCore.QSize(0, 50))
        self.wdg_titleArea.setObjectName("wdg_titleArea")
        self.lay_titleArea = QtWidgets.QHBoxLayout(self.wdg_titleArea)
        self.lay_titleArea.setContentsMargins(10, 10, 10, 10)
        self.lay_titleArea.setSpacing(3)
        self.lay_titleArea.setObjectName("lay_titleArea")
        self.lbl_pocketName = QtWidgets.QLabel(self.wdg_titleArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(140)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pocketName.sizePolicy().hasHeightForWidth())
        self.lbl_pocketName.setSizePolicy(sizePolicy)
        self.lbl_pocketName.setMinimumSize(QtCore.QSize(140, 0))
        self.lbl_pocketName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pocketName.setObjectName("lbl_pocketName")
        self.lay_titleArea.addWidget(self.lbl_pocketName)
        self.lbl_titleArrow = QtWidgets.QLabel(self.wdg_titleArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_titleArrow.sizePolicy().hasHeightForWidth())
        self.lbl_titleArrow.setSizePolicy(sizePolicy)
        self.lbl_titleArrow.setMinimumSize(QtCore.QSize(20, 0))
        self.lbl_titleArrow.setObjectName("lbl_titleArrow")
        self.lay_titleArea.addWidget(self.lbl_titleArrow)
        self.lbl_title = QtWidgets.QLabel(self.wdg_titleArea)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.lay_titleArea.addWidget(self.lbl_title)
        self.lay_central.addWidget(self.wdg_titleArea)
        self.wdg_contentArea = QtWidgets.QWidget(self)
        self.wdg_contentArea.setObjectName("wdg_contentArea")
        self.lay_contentArea = QtWidgets.QHBoxLayout(self.wdg_contentArea)
        self.lay_contentArea.setContentsMargins(0, 0, 0, 0)
        self.lay_contentArea.setSpacing(0)
        self.lay_contentArea.setObjectName("lay_contentArea")
        self.wdg_inputArea = QtWidgets.QWidget(self.wdg_contentArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_inputArea.sizePolicy().hasHeightForWidth())
        self.wdg_inputArea.setSizePolicy(sizePolicy)
        self.wdg_inputArea.setMinimumSize(QtCore.QSize(320, 295))
        self.wdg_inputArea.setObjectName("wdg_inputArea")
        self.lay_inputArea = QtWidgets.QVBoxLayout(self.wdg_inputArea)
        self.lay_inputArea.setContentsMargins(1, 1, 1, 1)
        self.lay_inputArea.setSpacing(1)
        self.lay_inputArea.setObjectName("lay_inputArea")
        self.wdg_settingsArea = QtWidgets.QWidget(self.wdg_inputArea)
        self.wdg_settingsArea.setObjectName("wdg_settingsArea")
        self.lay_settingsArea = QtWidgets.QVBoxLayout(self.wdg_settingsArea)
        self.lay_settingsArea.setContentsMargins(1, 1, 1, 1)
        self.lay_settingsArea.setSpacing(1)
        self.lay_settingsArea.setObjectName("lay_settingsArea")
        self.wdg_importArea = QtWidgets.QWidget(self.wdg_settingsArea)
        self.wdg_importArea.setObjectName("wdg_importArea")
        self.lay_importArea = QtWidgets.QHBoxLayout(self.wdg_importArea)
        self.lay_importArea.setContentsMargins(1, 1, 1, 1)
        self.lay_importArea.setSpacing(6)
        self.lay_importArea.setObjectName("lay_importArea")
        self.cmb_categories = QtWidgets.QComboBox(self.wdg_importArea)
        self.cmb_categories.setObjectName("cmb_categories")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        # self.cmb_categories.addItem("")
        self.lay_importArea.addWidget(self.cmb_categories)
        self.btn_importTool = QtWidgets.QPushButton(self.wdg_importArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_importTool.sizePolicy().hasHeightForWidth())
        self.btn_importTool.setSizePolicy(sizePolicy)
        self.btn_importTool.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_importTool.setObjectName("btn_importTool")
        self.lay_importArea.addWidget(self.btn_importTool)
        self.lay_settingsArea.addWidget(self.wdg_importArea)
        self.wdg_toolsArea = QtWidgets.QWidget(self.wdg_settingsArea)
        self.wdg_toolsArea.setObjectName("wdg_toolsArea")
        self.lay_toolsArea = QtWidgets.QHBoxLayout(self.wdg_toolsArea)
        self.lay_toolsArea.setContentsMargins(1, 1, 1, 1)
        self.lay_toolsArea.setSpacing(1)
        self.lay_toolsArea.setObjectName("lay_toolsArea")
        self.lst_tools = QtWidgets.QListWidget(self.wdg_toolsArea)
        self.lst_tools.setObjectName("lst_tools")
        self.lst_tools.setAlternatingRowColors(True)
        self.lst_tools.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lay_toolsArea.addWidget(self.lst_tools)
        self.wdg_selectArea = QtWidgets.QWidget(self.wdg_toolsArea)
        self.wdg_selectArea.setObjectName("wdg_selectArea")
        self.lay_selectArea = QtWidgets.QVBoxLayout(self.wdg_selectArea)
        self.lay_selectArea.setContentsMargins(1, 1, 1, 1)
        self.lay_selectArea.setSpacing(6)
        self.lay_selectArea.setObjectName("lay_selectArea")
        self.btn_addTool = QtWidgets.QPushButton(self.wdg_selectArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addTool.sizePolicy().hasHeightForWidth())
        self.btn_addTool.setSizePolicy(sizePolicy)
        self.btn_addTool.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_addTool.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_addTool.setObjectName("btn_addTool")
        self.lay_selectArea.addWidget(self.btn_addTool)
        self.btn_removeTool = QtWidgets.QPushButton(self.wdg_selectArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_removeTool.sizePolicy().hasHeightForWidth())
        self.btn_removeTool.setSizePolicy(sizePolicy)
        self.btn_removeTool.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_removeTool.setMaximumSize(QtCore.QSize(25, 16777215))
        self.btn_removeTool.setObjectName("btn_removeTool")
        self.lay_selectArea.addWidget(self.btn_removeTool)
        self.lay_toolsArea.addWidget(self.wdg_selectArea)
        self.lay_settingsArea.addWidget(self.wdg_toolsArea)
        self.lay_inputArea.addWidget(self.wdg_settingsArea)
        self.wdg_outputArea = QtWidgets.QWidget(self.wdg_inputArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_outputArea.sizePolicy().hasHeightForWidth())
        self.wdg_outputArea.setSizePolicy(sizePolicy)
        self.wdg_outputArea.setMinimumSize(QtCore.QSize(0, 25))
        self.wdg_outputArea.setObjectName("wdg_outputArea")
        self.lay_outputArea = QtWidgets.QHBoxLayout(self.wdg_outputArea)
        self.lay_outputArea.setContentsMargins(1, 1, 1, 1)
        self.lay_outputArea.setSpacing(6)
        self.lay_outputArea.setObjectName("lay_outputArea")
        self.btn_cancel = QtWidgets.QPushButton(self.wdg_outputArea)
        self.btn_cancel.setObjectName("btn_cancel")
        self.lay_outputArea.addWidget(self.btn_cancel)
        self.btn_edit = QtWidgets.QPushButton(self.wdg_outputArea)
        self.btn_edit.setObjectName("btn_edit")
        self.lay_outputArea.addWidget(self.btn_edit)
        self.lay_inputArea.addWidget(self.wdg_outputArea)
        self.lay_contentArea.addWidget(self.wdg_inputArea)
        self.wdg_previewArea = QtWidgets.QWidget(self.wdg_contentArea)
        self.wdg_previewArea.setMinimumSize(QtCore.QSize(220, 0))
        self.wdg_previewArea.setObjectName("wdg_previewArea")
        self.lay_previewArea = QtWidgets.QVBoxLayout(self.wdg_previewArea)
        self.lay_previewArea.setContentsMargins(1, 1, 1, 1)
        self.lay_previewArea.setSpacing(0)
        self.lay_previewArea.setObjectName("lay_previewArea")
        # self.lst_preview = QtWidgets.QListWidget(self.wdg_previewArea)
        # self.lst_preview.setObjectName("lst_preview")
        # self.lay_previewArea.addWidget(self.lst_preview)
        self.lay_contentArea.addWidget(self.wdg_previewArea)
        self.lay_central.addWidget(self.wdg_contentArea)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, gfutilitiesbelt_editpocketUI):
        _translate = QtCore.QCoreApplication.translate
        gfutilitiesbelt_editpocketUI.setWindowTitle(_translate(self.CONTROL_NAME, "gfUtilitiesBelt - Edit Pocket"))
        # self.lbl_pocketName.setText(_translate(self.CONTROL_NAME, "pocketName4Spaces    "))
        self.lbl_titleArrow.setText(_translate(self.CONTROL_NAME, ">"))
        self.lbl_title.setText(_translate(self.CONTROL_NAME, "Edit a existent pocket"))
        self.btn_importTool.setText(_translate(self.CONTROL_NAME, "Load Custom Tool"))
        self.btn_addTool.setText(_translate(self.CONTROL_NAME, "+"))
        self.btn_removeTool.setText(_translate(self.CONTROL_NAME, "-"))
        self.btn_cancel.setText(_translate(self.CONTROL_NAME, "Cancel"))
        self.btn_edit.setText(_translate(self.CONTROL_NAME, "Edit"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     gfutilitiesbelt_editpocketUI = QtWidgets.QDialog()
#     ui = Ui_gfutilitiesbelt_editpocketUI()
#     ui.setupUi(gfutilitiesbelt_editpocketUI)
#     gfutilitiesbelt_editpocketUI.show()
#     sys.exit(app.exec_())
