global proc AEgfDistributeAlongSurfaceTemplate (string $nodeName){
	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout "gfDistributeAlongSurface Attributes" -collapse 0;
			editorTemplate -callCustom ("AEinputNew \"Input Surface\"")
					("AEinputReplace \"Input Surface\"") "inputSurface";
            editorTemplate -addSeparator;
			editorTemplate -addControl "distributeAlong";
			editorTemplate -addControl "displaceTangent";
			editorTemplate -addControl "alwaysUniform";
		editorTemplate -endLayout;
		AEabstractBaseCreateTemplate $nodeName;
	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
}
